### ISSUE TITLE
字典太大的时候 扫描的时间会特别长

### ISSUE THREAD

**Issue by zhegege** [yanxiu0614/subdomain3#14]
我把sub_full修改到了181w+的字典 然后现在跑的时间特别长。。。。
用的-s 只跑一层
+] Bruting subdomain process domain: vipjr.com |scaned: 24495000|found: 46 |speed:308.2 |spend: 1324.7 min

**Comment by yanxiu0614** [comment]
目前发布的3.1已解决该问题，有问题可再反馈。
